spring:
  application:
    name: emailservice_re

  mail:
    host: smtp.163.com      # 163邮箱SMTP服务器地址
    port: 465              # SSL端口
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

server:
  port: 8080

grpc:
  server:
    port: 9090
